name: test
quality: 0.83323

repository:
  cat_boost_classifier: catboost.CatBoostClassifier

warehouse:
  data_path: 'input/'
  create_args:
    use_geo: False
    use_era5: False
    era5_metrics: '*'
    era5_years: '*'

featurise:
  calcers:
    dates_features: {}
    target_base: {}

pipeline:
  name: baseline_pipeline
  seed: 110894

  estimators:
    transformers: []
    selectors: 
      -
        dummy_selector: {}
    model:
      cat_boost_classifier: 
        iterations: 10
        auto_class_weights: Balanced

  fit_params: 
    model__verbose_eval: False

  split: {}

  search: {}