name: test

repository:
  fillna_transformer: sklearn.impute.SimpleImputer
  cat_boost_classifier: catboost.CatBoostClassifier

warehouse:
  data_path: 'input/'
  create_args:
    use_geo: False
    use_era5: False
    era5_metrics: '*'
    era5_years: '*'

featurise:
  calcers:
    dates_features: {}
    # geo_cat_features: {}
    # geo_neighbors_features: 
    #   count_neighbors: 5
    # grib_features: 
    #   metrics: '*'
    #   pooling_size: 3
    #   lags: [0, 1, 2, 3, ]
    #   agg_funcs: ['max', 'mean']
    target_base: {}

pipeline:
  name: baseline_pipeline
  seed: 110894

  estimators:
    transformers: []
    # - 
    #   name: geo_place
    #   columns: ['geo_place']
    #   estimators:
    #   -
    #     fillna_transformer:
    #       strategy: constant
    #       fill_value: NaN 
    selectors: 
      -
        dummy_selector: {}
    model:
      cat_boost_classifier: 
        cat_features: [0, ]
        iterations: 10
        auto_class_weights: Balanced

  fit_params: 
    model__verbose_eval: False

  split: {}

  search: {}